spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mocu
    username: root
    password: smartsj@0907
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
