spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3161a6ee6bf6b756c91d77d4f6003094
            client-secret: 3P0D0Tw8MeKiBN6NcY64sMlUBVvoSYux
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
      jwt:
        secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

  #jwt:
  #  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

  #oauth:
  #  kakao:
  #    client-id: 3161a6ee6bf6b756c91d77d4f6003094
  #    url:
  #      auth: https://kauth.kakao.com
  #      api: https://kapi.kakao.com


  #  datasource:
  #    url: jdbc:mysql://192.168.61.39:3306/mocu
  #    username: seongjin
  #    password: tjdwls1234!
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  #spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mocu
    username: root
    password: smartsj@0907
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
