spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          kakao1:
            client-id: 3161a6ee6bf6b756c91d77d4f6003094
            client-secret: 3P0D0Tw8MeKiBN6NcY64sMlUBVvoSYux
            redirect-uri: http://192.168.105.176:3000/login/user/oauth
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao1
            scope:
              - profile_nickname
              - profile_image
              - account_email
          kakao2:
            client-id: 3161a6ee6bf6b756c91d77d4f6003094
            client-secret: 3P0D0Tw8MeKiBN6NcY64sMlUBVvoSYux
            redirect-uri: http://192.168.105.176:3000/login/owner/oauth
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao2
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
      jwt:
        secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

oauth:
  kakao:
    client-id: 3161a6ee6bf6b756c91d77d4f6003094
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com


server:
#  ssl:
#    enabled : true
#    key-store : keystore.p12
#    key-store-passward : tjdwns1105!
#    key-store-type : PKCS12
#    key-alias : spring
  port: 9000